import Head from "next/head";

export default function header() {
  return (
    <Head>
        <title>VARIETY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}